name: Feature request
description: Idea or improvement for Voux
labels: [feature]
body:
  - type: textarea
    attributes:
      label: What do you want to see?
      description: Describe the feature simply.
      placeholder: I would love if Voux...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is it useful?
      description: Why would you or others need this?
      placeholder: This helps because...
  - type: textarea
    attributes:
      label: Extra context
      description: Screenshots, examples, or similar tools you like.
