name: Feature request
description: Idea or improvement for Voux
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What do you want to see?
      description: Describe the feature simply.
      placeholder: I would love if Voux...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is it useful?
      placeholder: This helps because...
  - type: textarea
    attributes:
      label: Extra context
      description: Screenshots, examples, or similar tools you like.
